apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "psc-portmapper.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "psc-portmapper.labels" . | nindent 4 }}
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs:
    - get
    - list
    - watch
    - patch
    - update
    - create
    - delete
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs:
    - get
    - list
    - watch
    - patch
    - update
  - apiGroups: [""]
    resources: ["services"]
    verbs:
    - list
    - watch
  - apiGroups: [""]
    resources: ["pods"]
    verbs:
    - list
    - watch
  - apiGroups: [""]
    resources: ["nodes"]
    verbs:
    - list
    - watch
