# https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#components
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
  namespace: ${ namespace }
  annotations:
    psc-portmapper.0x5d.org/spec: '{"prefix":"prefix-","nat_subnet_fqns":["${ nat_subnet }"],"node_ports":{"web":{"node_port":30000,"container_port":8080,"starting_port":30000}}}'
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: "nginx"
  replicas: 3
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: nginx
    spec:
      terminationGracePeriodSeconds: 10
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nginx
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: nginx
        image: registry.k8s.io/nginx-slim:0.24
        ports:
        - containerPort: 80
          name: web
