// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/0x5d/psc-portmapper/internal/gcp (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -destination mock/client.go -package mock . Client
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	computepb "cloud.google.com/go/compute/apiv1/computepb"
	gcp "github.com/0x5d/psc-portmapper/internal/gcp"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// AttachEndpoints mocks base method.
func (m *MockClient) AttachEndpoints(ctx context.Context, neg string, mappings []*gcp.PortMapping) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachEndpoints", ctx, neg, mappings)
	ret0, _ := ret[0].(error)
	return ret0
}

// AttachEndpoints indicates an expected call of AttachEndpoints.
func (mr *MockClientMockRecorder) AttachEndpoints(ctx, neg, mappings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachEndpoints", reflect.TypeOf((*MockClient)(nil).AttachEndpoints), ctx, neg, mappings)
}

// CreateBackendService mocks base method.
func (m *MockClient) CreateBackendService(ctx context.Context, name, neg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBackendService", ctx, name, neg)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBackendService indicates an expected call of CreateBackendService.
func (mr *MockClientMockRecorder) CreateBackendService(ctx, name, neg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBackendService", reflect.TypeOf((*MockClient)(nil).CreateBackendService), ctx, name, neg)
}

// CreateFirewall mocks base method.
func (m *MockClient) CreateFirewall(ctx context.Context, name string, ports map[int32]struct{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFirewall", ctx, name, ports)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateFirewall indicates an expected call of CreateFirewall.
func (mr *MockClientMockRecorder) CreateFirewall(ctx, name, ports any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFirewall", reflect.TypeOf((*MockClient)(nil).CreateFirewall), ctx, name, ports)
}

// CreateForwardingRule mocks base method.
func (m *MockClient) CreateForwardingRule(ctx context.Context, name, backendSvc string, ip *string, globalAccess *bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateForwardingRule", ctx, name, backendSvc, ip, globalAccess)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateForwardingRule indicates an expected call of CreateForwardingRule.
func (mr *MockClientMockRecorder) CreateForwardingRule(ctx, name, backendSvc, ip, globalAccess any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateForwardingRule", reflect.TypeOf((*MockClient)(nil).CreateForwardingRule), ctx, name, backendSvc, ip, globalAccess)
}

// CreatePortmapNEG mocks base method.
func (m *MockClient) CreatePortmapNEG(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePortmapNEG", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePortmapNEG indicates an expected call of CreatePortmapNEG.
func (mr *MockClientMockRecorder) CreatePortmapNEG(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePortmapNEG", reflect.TypeOf((*MockClient)(nil).CreatePortmapNEG), ctx, name)
}

// CreateServiceAttachment mocks base method.
func (m *MockClient) CreateServiceAttachment(ctx context.Context, name, fwdRuleFQN string, consumers []*computepb.ServiceAttachmentConsumerProjectLimit, natSubnetFQNs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateServiceAttachment", ctx, name, fwdRuleFQN, consumers, natSubnetFQNs)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateServiceAttachment indicates an expected call of CreateServiceAttachment.
func (mr *MockClientMockRecorder) CreateServiceAttachment(ctx, name, fwdRuleFQN, consumers, natSubnetFQNs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateServiceAttachment", reflect.TypeOf((*MockClient)(nil).CreateServiceAttachment), ctx, name, fwdRuleFQN, consumers, natSubnetFQNs)
}

// DeleteBackendService mocks base method.
func (m *MockClient) DeleteBackendService(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBackendService", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBackendService indicates an expected call of DeleteBackendService.
func (mr *MockClientMockRecorder) DeleteBackendService(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBackendService", reflect.TypeOf((*MockClient)(nil).DeleteBackendService), ctx, name)
}

// DeleteFirewall mocks base method.
func (m *MockClient) DeleteFirewall(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFirewall", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFirewall indicates an expected call of DeleteFirewall.
func (mr *MockClientMockRecorder) DeleteFirewall(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFirewall", reflect.TypeOf((*MockClient)(nil).DeleteFirewall), ctx, name)
}

// DeleteForwardingRule mocks base method.
func (m *MockClient) DeleteForwardingRule(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteForwardingRule", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteForwardingRule indicates an expected call of DeleteForwardingRule.
func (mr *MockClientMockRecorder) DeleteForwardingRule(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteForwardingRule", reflect.TypeOf((*MockClient)(nil).DeleteForwardingRule), ctx, name)
}

// DeletePortmapNEG mocks base method.
func (m *MockClient) DeletePortmapNEG(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePortmapNEG", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePortmapNEG indicates an expected call of DeletePortmapNEG.
func (mr *MockClientMockRecorder) DeletePortmapNEG(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePortmapNEG", reflect.TypeOf((*MockClient)(nil).DeletePortmapNEG), ctx, name)
}

// DeleteServiceAttachment mocks base method.
func (m *MockClient) DeleteServiceAttachment(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteServiceAttachment", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteServiceAttachment indicates an expected call of DeleteServiceAttachment.
func (mr *MockClientMockRecorder) DeleteServiceAttachment(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteServiceAttachment", reflect.TypeOf((*MockClient)(nil).DeleteServiceAttachment), ctx, name)
}

// DetachEndpoints mocks base method.
func (m *MockClient) DetachEndpoints(ctx context.Context, neg string, mappings []*gcp.PortMapping) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetachEndpoints", ctx, neg, mappings)
	ret0, _ := ret[0].(error)
	return ret0
}

// DetachEndpoints indicates an expected call of DetachEndpoints.
func (mr *MockClientMockRecorder) DetachEndpoints(ctx, neg, mappings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetachEndpoints", reflect.TypeOf((*MockClient)(nil).DetachEndpoints), ctx, neg, mappings)
}

// GetBackendService mocks base method.
func (m *MockClient) GetBackendService(ctx context.Context, name string) (*computepb.BackendService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBackendService", ctx, name)
	ret0, _ := ret[0].(*computepb.BackendService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBackendService indicates an expected call of GetBackendService.
func (mr *MockClientMockRecorder) GetBackendService(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBackendService", reflect.TypeOf((*MockClient)(nil).GetBackendService), ctx, name)
}

// GetFirewall mocks base method.
func (m *MockClient) GetFirewall(ctx context.Context, name string) (*computepb.Firewall, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFirewall", ctx, name)
	ret0, _ := ret[0].(*computepb.Firewall)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFirewall indicates an expected call of GetFirewall.
func (mr *MockClientMockRecorder) GetFirewall(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFirewall", reflect.TypeOf((*MockClient)(nil).GetFirewall), ctx, name)
}

// GetForwardingRule mocks base method.
func (m *MockClient) GetForwardingRule(ctx context.Context, name string) (*computepb.ForwardingRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetForwardingRule", ctx, name)
	ret0, _ := ret[0].(*computepb.ForwardingRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetForwardingRule indicates an expected call of GetForwardingRule.
func (mr *MockClientMockRecorder) GetForwardingRule(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetForwardingRule", reflect.TypeOf((*MockClient)(nil).GetForwardingRule), ctx, name)
}

// GetNEG mocks base method.
func (m *MockClient) GetNEG(ctx context.Context, name string) (*computepb.NetworkEndpointGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNEG", ctx, name)
	ret0, _ := ret[0].(*computepb.NetworkEndpointGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNEG indicates an expected call of GetNEG.
func (mr *MockClientMockRecorder) GetNEG(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNEG", reflect.TypeOf((*MockClient)(nil).GetNEG), ctx, name)
}

// GetServiceAttachment mocks base method.
func (m *MockClient) GetServiceAttachment(ctx context.Context, name string) (*computepb.ServiceAttachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceAttachment", ctx, name)
	ret0, _ := ret[0].(*computepb.ServiceAttachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceAttachment indicates an expected call of GetServiceAttachment.
func (mr *MockClientMockRecorder) GetServiceAttachment(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceAttachment", reflect.TypeOf((*MockClient)(nil).GetServiceAttachment), ctx, name)
}

// ListEndpoints mocks base method.
func (m *MockClient) ListEndpoints(ctx context.Context, neg string) ([]*gcp.PortMapping, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEndpoints", ctx, neg)
	ret0, _ := ret[0].([]*gcp.PortMapping)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEndpoints indicates an expected call of ListEndpoints.
func (mr *MockClientMockRecorder) ListEndpoints(ctx, neg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEndpoints", reflect.TypeOf((*MockClient)(nil).ListEndpoints), ctx, neg)
}

// Project mocks base method.
func (m *MockClient) Project() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Project")
	ret0, _ := ret[0].(string)
	return ret0
}

// Project indicates an expected call of Project.
func (mr *MockClientMockRecorder) Project() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Project", reflect.TypeOf((*MockClient)(nil).Project))
}

// Region mocks base method.
func (m *MockClient) Region() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Region")
	ret0, _ := ret[0].(string)
	return ret0
}

// Region indicates an expected call of Region.
func (mr *MockClientMockRecorder) Region() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Region", reflect.TypeOf((*MockClient)(nil).Region))
}

// UpdateFirewall mocks base method.
func (m *MockClient) UpdateFirewall(ctx context.Context, name string, ports map[int32]struct{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFirewall", ctx, name, ports)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFirewall indicates an expected call of UpdateFirewall.
func (mr *MockClientMockRecorder) UpdateFirewall(ctx, name, ports any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFirewall", reflect.TypeOf((*MockClient)(nil).UpdateFirewall), ctx, name, ports)
}
